# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(529, 595)
        Form.setStyleSheet("QLineEdit{\n"
"    border: 3px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border-left: 1px solid gray;\n"
"    width: 25px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    image: url(:/icons/icons/down-arrow.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow::hover{\n"
"    \n"
"    image: url(:/icons/icons/expand_circle_down_FILL0_wght400_GRAD0_opsz24.ico);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QDateEdit{\n"
"    border: 3px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow, QDateEdit::up-arrow {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QDateEdit::down-button, QDateEdit::up-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 507, 544))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(25, 340, 141, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setGeometry(QtCore.QRect(255, 340, 141, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.layoutWidget_5 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(50, 10, 361, 47))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_7.addWidget(self.comboBox_6)
        self.layoutWidget_6 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(50, 120, 361, 47))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_6)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_8.addWidget(self.comboBox_3)
        self.layoutWidget_7 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 240, 229, 64))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkBox_2.setMinimumSize(QtCore.QSize(201, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_9.addWidget(self.checkBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(131, 22))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(131, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.layoutWidget_8 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(250, 240, 229, 64))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.checkBox_4.setMinimumSize(QtCore.QSize(221, 31))
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_10.addWidget(self.checkBox_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_8)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(131, 22))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(131, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_4.addWidget(self.lineEdit_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.lineEdit_4.hide()
        self.lineEdit_6.hide()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Variaveis"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "Valor Proposta R$"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "Valor Consultoria R$"))
        self.label_7.setText(_translate("Form", "Contratante"))
        self.label_4.setText(_translate("Form", "Corretor"))
        self.checkBox_2.setText(_translate("Form", "Mudança no valor Mínimo ?"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "R$ "))
        self.checkBox_4.setText(_translate("Form", "Mudança no valor de Avaliação ?"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "R$ "))
from front.static import resource
