# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'administracao_locacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(626, 588)
        Form.setStyleSheet("QLineEdit{\n"
"    border: 3px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border-left: 1px solid gray;\n"
"    width: 25px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    image: url(:/icons/icons/down-arrow.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow::hover{\n"
"    \n"
"    image: url(:/icons/icons/expand_circle_down_FILL0_wght400_GRAD0_opsz24.ico);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 0px;\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 350, 121, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(250, 500, 121, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(390, 350, 121, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(250, 400, 121, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(250, 450, 121, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(390, 500, 121, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(250, 350, 121, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(390, 400, 121, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(390, 450, 121, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(320, 550, 121, 22))
        self.lineEdit_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 60, 532, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_2.setMinimumSize(QtCore.QSize(80, 0))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_9.addWidget(self.radioButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_10.addWidget(self.comboBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(13, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_5.setEnabled(False)
        self.comboBox_5.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_10.addWidget(self.comboBox_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 190, 341, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(339, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout.addWidget(self.comboBox_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Variaveis"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Porcertagem"))
        self.lineEdit_13.setPlaceholderText(_translate("Form", "Monobitrifasico"))
        self.lineEdit_16.setPlaceholderText(_translate("Form", "Nº Cons D\'Água"))
        self.lineEdit_9.setPlaceholderText(_translate("Form", "Inscrição IPTU"))
        self.lineEdit_10.setPlaceholderText(_translate("Form", "Relogio"))
        self.lineEdit_11.setPlaceholderText(_translate("Form", "Matricula"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "Cartorio"))
        self.lineEdit_14.setPlaceholderText(_translate("Form", "Nº Cons Gás"))
        self.lineEdit_15.setPlaceholderText(_translate("Form", "Funesbom"))
        self.lineEdit_12.setPlaceholderText(_translate("Form", "Nº Cons Luz"))
        self.label_9.setText(_translate("Form", "Escolha o Locador"))
        self.label_4.setText(_translate("Form", "Corretor"))
from front.static import resource
