# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'locacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(552, 597)
        Form.setStyleSheet("QLineEdit{\n"
"    border: 3px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border-left: 1px solid gray;\n"
"    width: 25px;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    image: url(:/icons/icons/down-arrow.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow::hover{\n"
"    \n"
"    image: url(:/icons/icons/expand_circle_down_FILL0_wght400_GRAD0_opsz24.ico);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QDateEdit{\n"
"    border: 3px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow, QDateEdit::up-arrow {\n"
"    border: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QDateEdit::down-button, QDateEdit::up-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(11, 11, 82, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(11, 40, 531, 541))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -530, 514, 1071))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(510, 1071))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(20, 20, 488, 1071))
        self.widget.setMinimumSize(QtCore.QSize(488, 523))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 250, 171, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 390, 171, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(175, 200, 121, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setGeometry(QtCore.QRect(-2, 290, 481, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(185, 350, 101, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(140, 460, 16, 311))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(330, 460, 16, 311))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(5, 650, 131, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(0, 610, 151, 31))
        self.checkBox.setObjectName("checkBox")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(0, 520, 471, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(19, 450, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(190, 450, 101, 31))
        self.label_5.setObjectName("label_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 530, 151, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(5, 570, 131, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setGeometry(QtCore.QRect(160, 530, 181, 31))
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 570, 131, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(350, 490, 121, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(390, 450, 51, 31))
        self.label_6.setObjectName("label_6")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setGeometry(QtCore.QRect(160, 610, 151, 31))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setGeometry(QtCore.QRect(350, 530, 121, 31))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 690, 161, 31))
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(5, 730, 131, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_7.setGeometry(QtCore.QRect(160, 650, 151, 31))
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(350, 570, 131, 31))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_8.setGeometry(QtCore.QRect(350, 610, 71, 31))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_9.setGeometry(QtCore.QRect(350, 650, 71, 31))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_10.setGeometry(QtCore.QRect(160, 690, 171, 31))
        self.checkBox_10.setAcceptDrops(False)
        self.checkBox_10.setAutoFillBackground(False)
        self.checkBox_10.setTristate(False)
        self.checkBox_10.setObjectName("checkBox_10")
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setGeometry(QtCore.QRect(5, 490, 131, 22))
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.widget)
        self.dateEdit_2.setGeometry(QtCore.QRect(170, 490, 131, 22))
        self.dateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setGeometry(QtCore.QRect(0, 140, 481, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setGeometry(QtCore.QRect(150, 70, 171, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(175, 20, 121, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.checkBox_11 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_11.setGeometry(QtCore.QRect(350, 690, 151, 31))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 880, 71, 31))
        self.checkBox_12.setObjectName("checkBox_12")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 830, 181, 31))
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(False)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.checkBox_13 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_13.setGeometry(QtCore.QRect(100, 880, 71, 31))
        self.checkBox_13.setObjectName("checkBox_13")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(190, 780, 16, 311))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setGeometry(QtCore.QRect(210, 800, 121, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(210, 850, 121, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setGeometry(QtCore.QRect(210, 900, 121, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setGeometry(QtCore.QRect(350, 950, 121, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setGeometry(QtCore.QRect(280, 1000, 121, 22))
        self.lineEdit_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setGeometry(QtCore.QRect(210, 950, 121, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setGeometry(QtCore.QRect(350, 850, 121, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setGeometry(QtCore.QRect(350, 900, 121, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_16.setGeometry(QtCore.QRect(350, 800, 121, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.lineEdit_3.hide()
        self.lineEdit_4.hide()
        self.lineEdit_5.hide()
        self.lineEdit_7.hide()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Variaveis"))
        self.label_3.setText(_translate("Form", "Parte Locadora"))
        self.label_4.setText(_translate("Form", "Corretor"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "R$ "))
        self.checkBox.setText(_translate("Form", "Mudança no aluguel ?"))
        self.label_2.setText(_translate("Form", "Prazo do Contrato"))
        self.label_5.setText(_translate("Form", "Inicio do Contrato"))
        self.checkBox_2.setText(_translate("Form", "Mudança no IPTU ?"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "R$ "))
        self.checkBox_3.setText(_translate("Form", "Mudança no Condominio ?"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "R$ "))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "R$ "))
        self.label_6.setText(_translate("Form", "Seguro"))
        self.checkBox_4.setText(_translate("Form", "Fica em Condominio ?"))
        self.checkBox_5.setText(_translate("Form", "Aceita animais ?"))
        self.checkBox_6.setText(_translate("Form", "Maximo moradores"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "1 ou Mais"))
        self.checkBox_7.setText(_translate("Form", "Alienado ?"))
        self.label_7.setText(_translate("Form", "Relatorio de Entrega de chaves"))
        self.checkBox_8.setText(_translate("Form", "Agora ?"))
        self.checkBox_9.setText(_translate("Form", "Pós ?"))
        self.checkBox_10.setText(_translate("Form", "Inquilino pagará os \n"
"encargos de alocação ?"))
        self.dateEdit.setDisplayFormat(_translate("Form", "MM"))
        self.label_8.setText(_translate("Form", "Parte Locataria"))
        self.checkBox_11.setText(_translate("Form", "Garagem ?"))
        self.checkBox_12.setText(_translate("Form", "Agora ?"))
        self.label_9.setText(_translate("Form", "Vistoria enviado agora ou após entrega das chaves"))
        self.checkBox_13.setText(_translate("Form", "Pós ?"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "Cartorio"))
        self.lineEdit_9.setPlaceholderText(_translate("Form", "Inscrição IPTU"))
        self.lineEdit_10.setPlaceholderText(_translate("Form", "Relogio"))
        self.lineEdit_11.setPlaceholderText(_translate("Form", "Matricula"))
        self.lineEdit_12.setPlaceholderText(_translate("Form", "Nº Cons Luz"))
        self.lineEdit_13.setPlaceholderText(_translate("Form", "Monobitrifasico"))
        self.lineEdit_14.setPlaceholderText(_translate("Form", "Nº Cons Gás"))
        self.lineEdit_15.setPlaceholderText(_translate("Form", "Funesbom"))
        self.lineEdit_16.setPlaceholderText(_translate("Form", "Nº Cons D\'Água"))
from front.static import resource
